server:
  error:
    include-message: always
    include-binding-errors: always

  port: 8081

spring:
  datasource:
    username: postgres
    password: '@Potter77'
    url: jdbc:postgresql://localhost:5432/authentication

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  mail:
    host: smtp.gmail.com
    username: ${EMAIL_ADDRESS}
    password: ${EMAIL_PASSWORD}
    port: 587

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

    protocol: smtp
    default-encoding: utf-8
    test-connection: true
    jndi-name: mail/Session

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  show-actuator: true
  api-docs:
    enabled: true
    path: /api-docs

