server:
  error:
    include-message: always
    include-binding-errors: always

  port: 8080

spring:
  datasource:
    username: postgres
    password: '@Potter77'
    url: jdbc:postgresql://localhost:5432/authentication

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  show-actuator: true
  api-docs:
    enabled: true
    path: /api-docs